name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-lastest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4    

         

        - name: List and Read Files
          run: |
            echo "My first GitHub Actions Job"
            ls -la
            cat README.md 
             
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a dragon...rawr" >> dragon.txt   
        #- name: Read File
        #  run: cat README.md  